Fix clippy::result_large_err linter error
This suppresses the following Clippy error:

    error: the `Err`-variant returned from this closure is very large

Tungstenite's `Callback` trait dictates the `Err` type as
`Response<Option<String>>`, so we cannot box it.